version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: standard
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close
        - (*github.com/zx06/xsql/internal/ssh.Client).Close
        - (io.Closer).Close

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zx06/xsql
