# Codecov config
# Docs: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    # Project overall coverage
    project:
      default:
        target: auto        # Use baseline branch coverage as target
        threshold: 5%       # Allow 5% coverage drop
        if_ci_failed: error
    # New code (patch) coverage
    patch:
      default:
        target: 80%         # New code coverage at least 80%
        threshold: 10%      # Allow 10% variance

# Ignored files/directories
ignore:
  - "**/*_test.go"         # Do not count test files toward coverage
